# -*- coding: utf-8 -*-
"""yolodetection1002.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/169eQuPRAxpOVNjcaITnUGCmA2EEPtT2P
"""

!git clone https://github.com/ultralytics/ultralytics.git

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics

dependencies = [
    "numpy",
    "matplotlib",
    "opencv-python",
    "pillow",
    "pyyaml",
    "requests",
    "scipy",
    "torch",
    "torchvision",
    "psutil",
    "polars",
    "ultralytics-thop",
]

for dep in dependencies:
    print(f"Checking {dep}:")
    !pip show {dep}
    print("-" * 20)

import os

# create videos folder to store data.
folder_path = '/content/ultralytics/ultralytics/videos'

if not os.path.exists(folder_path):
    os.makedirs(folder_path)
    print(f"Folder '{folder_path}' created.")
else:
    print(f"Folder '{folder_path}' already exists.")

from ultralytics import YOLO
import os

# Load a pre-trained YOLO model ('yolov8s.pt' kinda doo doo. get an upgrade [s, m, l])
model = YOLO('yolov8l.pt')

# Folder containing videos
video_folder = '/content/ultralytics/ultralytics/videos' # input folder (put videos here)
output_folder = '/content/ultralytics/ultralytics/all_videos_output' # output folder (view videos with detetections here)
os.makedirs(output_folder, exist_ok=True)

# Get list of video files
video_files = [
    os.path.join(video_folder, f)
    for f in os.listdir(video_folder)
    if f.endswith(('.mp4', '.avi', '.mov'))
]

# Check if any videos were found
if not video_files:
    print(f"No video files found in {video_folder}")
else:
    print(f"Found {len(video_files)} videos to look at.")

# Process each video file individually and save results to a single folder (gonna take rlly long maybe find a way to run them in multiple processes?)
for video_index, video_path in enumerate(video_files):
    print(f"Processing video {video_index + 1}/{len(video_files)}: {os.path.basename(video_path)}")

    # Run YOLOv8 on the current video
    # conf = will box the detected players with 0.X confidence.
    # iou = if boxes overlap by 0.X, keep the one with the highest confidence (maybe set it high cause some sports require close contact)
    results = model.predict(
        source=video_path,
        classes=[0],
        stream=False,
        save=True,
        conf=0.35,
        iou=0.9,
        project='project=output_folder',
        name='',  # All outputs go into the same folder (name above)
        exist_ok=True
    )

    # Iterate through results (one per frame)
    for i, result in enumerate(results):
        detections = result.boxes
        num_people = len(detections)
        print(f"  Video {video_index + 1}, Frame {i}: Detected {num_people} people")