# -*- coding: utf-8 -*-
"""yolodetection0312.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_AtEvIYkkJl1II6RnH9ygMd70Xq6_KFs

Directions:
1) Run All and wait a bit for ultralytics, its dependencies and files
2) Drag and drop video files (avi, mp4, mov) into content->ultralytics->ultralytics->videos
3) Run last cell to use yolo player detection on all files (~1-2 seconds per frame)
4) View detected files in content->ultralytics->ultralytics->all_videos_output
"""

!git clone https://github.com/ultralytics/ultralytics.git

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
# %pip uninstall torch torchvision torchaudio
# %pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

dependencies = [
    "numpy",
    "matplotlib",
    "opencv-python",
    "pillow",
    "pyyaml",
    "requests",
    "scipy",
    "torch",
    "torchvision",
    "psutil",
    "polars",
    "ultralytics-thop",
]

for dep in dependencies:
    print(f"Checking {dep}:")
    !pip show {dep}
    print("-" * 20)

import os

# create videos folder to store data.
folder_path = '/content/ultralytics/ultralytics/videos'

if not os.path.exists(folder_path):
    os.makedirs(folder_path)
    print(f"Folder '{folder_path}' created.")
else:
    print(f"Folder '{folder_path}' already exists.")

"""3/12 Changes:

Run cell below for detections. same instructions as the top description.
- conf = 0.35-0.45, iou = 0.8
- swapped from model.predict to model.track to be able to use bytetrack.yaml for "better" detections
- added batch & workers attribute to have more consistent run times. (detecting X frames at a time)
- video clip for comparison is 14 seconds long.
- Used different ranges of imgsz (image sizes) for detection. [sz640 = ~440 seconds, sz448 = ~382 seconds, sz416 = ~356 seconds, sz320 = ~220 seconds]
- lowering image size lowers run time, but lowers accuracy.
- Personally, sz416 works the best out of all of this so far. It was at sz640 during previous iterations (~10-25 min w/o applied methods). (except for the ball x player one sz992)
"""

from ultralytics import YOLO
import os
import time


# Load a pre-trained YOLO model ('yolov8s.pt' isnt good. get an upgrade [s, m, l])
model = YOLO('yolov8m.pt')
# model.to("cuda")

# Folder containing videos
video_folder = '/content/ultralytics/ultralytics/videos' # input folder (put videos here)
output_folder = '/content/ultralytics/ultralytics/all_videos_output' # output folder (view videos with detetections here)
os.makedirs(output_folder, exist_ok=True)

# Get list of video files
video_files = [
    os.path.join(video_folder, f)
    for f in os.listdir(video_folder)
    if f.endswith(('.mp4', '.avi', '.mov'))
]

# Check if any videos were found
if not video_files:
    print(f"No video files found in {video_folder}")
else:
    print(f"Found {len(video_files)} videos to look at.")

# instantiate time (this is to show how long this process takes)
start_time = time.time()
# Process each video file individually and save results to a single folder (gonna take rlly long maybe find a way to run them in multiple processes?)
for video_index, video_path in enumerate(video_files):
    print(f"Processing video {video_index + 1}/{len(video_files)}: {os.path.basename(video_path)}")

    # Run YOLOv8 on the current video
    # conf = will box the detected players if they are X% confident.
    # iou = if boxes overlap by X%, keep the one with the highest confidence (maybe set it high cause some sports require close contact)
    results = model.track( # replace predict with track
        source=video_path,
        classes=[0], #class[0] = people
        stream=True,
        imgsz=416, # try lowering image size for detection a bit? faster but tanks accuracy
        save=True,
        persist=True,
        conf=0.35, # get the right balance of being able to track players accurately whilst avoiding spectators on the side
        iou=0.8, # if the system thinks it's X percent confident that 2 detected are collided, detect the highest of the two.
        project=output_folder,
        name='',  # All outputs go into the same folder (name above)
        exist_ok=True,
        tracker="bytetrack.yaml", # ultralytics alr has bytetrack.
        batch=16, # run X detections at a time. allows for consistant run times.
        cache=True,
        workers=24, # not sure why but as long as workers >= batch, it makes running speed faster.
        # device=0,
        # vid_stride=4, # process every X seconds. makes it X times faster.
        # persist=True # make sure we keep the changes of vid_stride or else video will speed up X times.
    )

    # Iterate through results (one per frame)
    for i, result in enumerate(results):
        detections = result.boxes
        num_people = len(detections)
        print(f"  Video {video_index + 1}, Frame {i+1}: Detected {num_people} people")

end_time = time.time()
total_time = end_time - start_time
print(f"Total time taken: {total_time} second(s) ({total_time/60} minute(s)) to view {len(video_files)} files.")